### ISSUE TITLE
replace --devel with --version

### ISSUE THREAD

**Issue by bradrydzewski** [drone/homebrew-drone#3]
I would like to replace `--devel` with `--version={version}`

Example commands:

```
brew install drone --version=0.6.0
```

The downloads will follow a standard pattern for each release number:

```
http://downloads.drone.io/{version}/release/darwin/amd64/drone.tar.gz
http://downloads.drone.io/0.6.0/release/darwin/amd64/drone.tar.gz
http://downloads.drone.io/0.6.1/release/darwin/amd64/drone.tar.gz
http://downloads.drone.io/0.6.2/release/darwin/amd64/drone.tar.gz
http://downloads.drone.io/0.7.0/release/darwin/amd64/drone.tar.gz
...
```

If no version is provided:

```
brew install drone
```

We can assume it uses the `latest` version number. We can have a special path for the latest (head) version of the cli

```
http://downloads.drone.io/{version}/release/darwin/amd64/drone.tar.gz
http://downloads.drone.io/latest/release/darwin/amd64/drone.tar.gz
```

I think at this point we can also remove `--head` from the formula. When that was originally added we didn't publish the cli on every build, so it was necessary to build from source. This should no longer be necessary.

**Comment by tboerger** [comment]
Sounds like it makes sense
