### ISSUE TITLE
Brew cannot find versions

### ISSUE THREAD

**Issue by aaronkorver** [drone/homebrew-drone#8]
``brew switch drone 0.5
Error: drone does not have a version "0.5" in the Cellar.
Versions available: latest
``

@jmccann after your latest PR, does something need to be pushed into brew so it knows about the versions?

**Comment by tboerger** [comment]
`brew install drone@0.5` or `brew install drone@0.7`...

**Comment by aaronkorver** [comment]
🤦‍♂️   Yup, that works.  Thanks!
